### ISSUE TITLE
Quantum-Coin-Game.ipynb does not in interactive mode on binder

### ISSUE THREAD

**Issue by JanLahmann** [Qiskit/qiskit-community-tutorials#6]
### Informations

- **Qiskit version**: current
- **Python version**: current
- **Operating system**: any

### What is the current behavior?
When starting community/games/Quantum-Coin-Game.ipynb in binder it does not start the RISE interface, which is needed to play the game interactively.

### Steps to reproduce the problem
start https://mybinder.org/v2/gh/qiskit/qiskit-tutorials/master?filepath=community/games/Quantum-Coin-Game.ipynb
and compare to 
https://mybinder.org/v2/gh/JanLahmann/Fun-with-Quantum/master?filepath=Quantum-Coin-Game.ipynb

### What is the expected behavior?
The game should automatically start the interactive RISE interface.
This is needed to play the game interactively.

### Suggested solutions
add rise to environment.yml

**Comment by omarcostahamido** [comment]
On my way back from Qiskit Camp Europe right now. When I get home, I can take a look at this ;)

**Comment by omarcostahamido** [comment]
Hi @JanLahmann ,
Could you please confirm if my pull request #34 , that was very recently added, fixed this issue?
the first link you provided no longer works, and I do believe that is because "this repo was moved". The current link should be: https://mybinder.org/v2/gh/qiskit/qiskit-community-tutorials/master?filepath=./games/Quantum-Coin-Game.ipynb

Best,
Omat

**Comment by JanLahmann** [comment]
Yes, thank you, the issue is solved!
